// This file was autogenerated by sdk/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/hua/worktest/content.js', ['hua.worktest.Content'], ['goog.array', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.events.EventType', 'goog.fx.Animation', 'goog.fx.Transition', 'goog.fx.css3', 'goog.fx.dom', 'goog.fx.easing', 'goog.style', 'goog.ui.Dialog']);
goog.addDependency('../../../../src/hua/worktest/main.js', ['hua.worktest.main'], ['hua.worktest.Content']);
goog.addDependency('../../../../src/hua/worktest/test.js', ['tutorial.notepad', 'tutorial.notepad.Note'], ['goog.dom', 'goog.ui.Zippy']);
goog.addDependency('../../../../src/spring/spring2016/content.js', ['spring.spring2016.Content'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'pt.api.JsonpApi']);
goog.addDependency('../../../../src/spring/spring2016/hua.js', ['spring2015.pc.GiftSpring'], ['goog.array', 'goog.dom', 'goog.events', 'goog.events.EventType', 'pt.api.JsonpApi', 'pt.ui.LotteryRecord', 'pt.ui.sidenav.Scroll2', 'pt.ui.topbar.SmallTopbar']);
goog.addDependency('../../../../src/spring/spring2016/main.js', ['spring.spring2016.main'], ['spring.spring2016.Content']);
